[package]
name = "poh-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
sha2 = "0.10.8"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
